### ISSUE TITLE
What are the differences and major improvements? 

### ISSUE THREAD

**Issue by l1va** [samuelsadok/fibre#14]
Hi, Samuel!
Thank you for the interesting project!
My colleagues work with ODrive and I found that API is pretty beautiful. 
Even more - I think about the implementation library for golang. 
But I have some questions. 

It will be great if you have time to chat in telegram ( @l1va4ka ) or you can send other contacts by email (m.ivanov@innopolis.ru) to not post it here. 

Firstly i would like to ask about the whole idea. I read everything that i found (sources in different branches), but i think i can't clearly answer the question why not to use uavcan, profinet, nats, mqtt or something else as a transport layer? Might be because i am not so strong on hardware side and not so strong in c programming it is not obvious for me. Or do you see any other more closer competitor? Ros is decided to use dds for example. Is it "too large"? 

Thank you for your time.

Best regards, Mike.

**Comment by samuelsadok** [comment]
Hey Mike!
Thanks for your interest in the project!

There are several aspects to a communication framework which I find rather important and most of which are found in _some_ existing communication frameworks but I don't know any framework yet which combines all those aspects (including Fibre, but we're moving there). Here's an incomplete list:

 - Automatic discovery of objects that match a certain interface
 - High level API (remote procedure calls rather than sending raw bytes)
   Now sometimes passing raw bytes may actually be exactly what you want and there are other paradigms (publish-subscribe, message passing) which have their place too. But often you'd like to use several of these paradigms side-by-side in the same application. For example for a motor controller's position command and feedback a publish-subscribe scheme makes sense, but for a command like "save configuration to NVM" a function call is more appropriate. It turns out that a variation of function calls (remote procedure call with infinite-length input and output streams instead of finite argument list) makes it easy to have subscriptions and traditional function calls side-by-side.
 - The high level API should optionally be announcable by the server itself so that the client doesn't need to be recompiled with every new server feature.
 - Not bound to a particular underlying layer (not bound to USB-only or CAN-only)
 - Automatic discovery of communication paths (including multi-hop) and automatic switch-over or link-bundling in the face of dynamic network topologies
 - Suitable to run on _any_ platform (bare-metal embedded, desktop, mobile, web, ...)
 - Suitable to use from multiple programming languages

(again note that Fibre, too, doesn't cover all of this yet but design decisions are made with those things in mind)

For ODrive in particular some of these features may seem unnecessary initially but as ODrive evolves so do its communication requirements and things which seemed far-off (like multi-hop capability) suddenly become very relevant (e.g. controlling an ODrive testrig from the developer PC via a Raspberry Pi).

If you're interested in implementing golang bindings that would be cool! Since recently there's [a C library](https://github.com/samuelsadok/fibre/blob/devel/cpp/include/fibre/libfibre.h) which you can just bind to rather than implementing the whole protocol. In fact the protocol itself will soon require changes to scale towards the aforementioned goals but implementations that bind to the C/C++ libfibre will be largely (albeit not completely) shielded from those changes.

If you have any questions regarding the libfibre API or otherwise let me know! You can find me on the [ODrive Discord](https://discord.gg/k3ZZ3mS) as "Samuel#7161".

**Comment by l1va** [comment]
Thank you for the answer!
