### ISSUE TITLE
Add ARM64 support

### ISSUE THREAD

**Issue by hbuhle2s** [samuelsadok/fibre#17]
Hi,
I'm currently using ODrive with the Jetson Nano and the new 0.5.2 release seems not to work properly, because the binary for arm64 is not included here.
Thanks!

**Comment by samuelsadok** [comment]
AArch64 support is meanwhile on fibre's `devel` branch. You can find the binaries in the build artifacts of the most recent devel commit: https://github.com/samuelsadok/fibre/actions/runs/755558483

When you say "I'm running 0.5.2" I believe you mean you're running odrivetool directly from ODrive's devel branch because there is no 0.5.2 release yet. If that's the case, you can copy paste fibre's "python" directory to replace ODrive's "tools/odrive/fibre" directory and then place your desired binaries in there.

**Comment by hbuhle2s** [comment]
Hi,
sorry for being unclear. Yes, I'm running odrive from the develbranch, and I already got it working by manually compiling fibre. But it would be nice if the next odrive release works out of the box on arm64 platforms, so I wanted to mention this before the release is out.
Thanks again!

**Comment by samuelsadok** [comment]
Ok understood! I checked and can confirm that AArch64 support will be part of the upcoming odrivetool 0.5.2 release.
